"""
    ContractAgent takes a JSON dictionary (as generated by QuotationAgent)
    and generates a professional, legally-structured PDF contract.
"""
# How to use ContractAgent:
# 1. Load JSON file: agent = ContractAgent.from_json_file("contract_data.json")
# 2. Generate PDF: pdf_path = agent.generate_contract_pdf()
# 3. Print path: print(pdf_path)

from typing import Dict, Any
from fpdf import FPDF
import json
import datetime
import os
import re

class ContractAgent:
    """Pull from QuotationAgent JSON directory"""
    def __init__(self, contract_json: Dict[str, Any]):
        self.data = contract_json

    def _format_date(self, date_str: str) -> tuple:
        """Converts YYYY-MM-DD to formatted date tuple (day, month, year)"""
        try:
            date_obj = datetime.datetime.strptime(date_str, "%Y-%m-%d")
            day = date_obj.strftime("%d").lstrip('0') or '1'
            month = date_obj.strftime("%B")
            year = date_obj.strftime("%Y")
            return (day, month, year)
        except:
            return ("___", "___", "___")

    def _split_text(self, pdf: FPDF, text: str, max_width: float) -> list:
        """Splits text into lines that fit within max_width using FPDF's width calculation"""
        words = text.split()
        if not words:
            return [text]
        
        lines = []
        current_line = []
        
        for word in words:
            test_line = ' '.join(current_line + [word])
            # Use FPDF's get_string_width for accurate measurement
            width = pdf.get_string_width(test_line)
            
            if width > max_width and current_line:
                lines.append(' '.join(current_line))
                current_line = [word]
            else:
                current_line.append(word)
        
        if current_line:
            lines.append(' '.join(current_line))
        
        return lines if lines else [text]

    def generate_contract_pdf(self, output_path: str = None) -> str:
        """
        Generates a professional PDF contract and returns its file path.
        """
        pdf = FPDF(format='A4')
        pdf.set_auto_page_break(auto=True, margin=20)
        pdf.add_page()
        
        # Get contract data
        c = self.data.get("contract_data", {})
        buyer = self.data.get("buyer_company", {})
        supplier = self.data.get("supplier_company", {})
        prod = self.data.get("product_details", {})
        terms = self.data.get("contract_terms", {})
        deliver = self.data.get("delivery_information", {})
        
        # Replace [Product Name] placeholder if present
        contract_title = c.get("contract_title", "SUPPLIER AGREEMENT")
        if "[Product Name]" in contract_title:
            product_name = prod.get("product_name", "")
            contract_title = contract_title.replace("[Product Name]", product_name)
        
        # Format date
        date_str = c.get("date_of_agreement", "")
        day, month, year = self._format_date(date_str)
            
        # Main Title
        pdf.set_font('Arial', 'B', 16)
        pdf.cell(0, 12, contract_title.upper(), ln=1, align='C')
        pdf.ln(5)
        
        # Agreement Header
        pdf.set_font('Arial', '', 11)
        agreement_text = f'THIS AGREEMENT (the "Agreement") is made this {day} day of {month}, {year} (the "Effective Date").'
        for line in self._split_text(pdf, agreement_text, 170):
            pdf.cell(0, 6, line, ln=1)
        pdf.ln(3)
        pdf.cell(0, 6, "BETWEEN:", ln=1)
        pdf.ln(2)
        
        # Parties Section
        pdf.set_font('Arial', '', 10)
        buyer_name = buyer.get("name", "[BUYER COMPANY NAME]")
        buyer_reg = buyer.get("registration_number", "[REGISTRATION NUMBER]")
        buyer_addr = buyer.get("address", "[ADDRESS]")
        buyer_state = self._extract_state(buyer_addr)
        
        supplier_name = supplier.get("name", "[SUPPLIER COMPANY NAME]")
        supplier_reg = supplier.get("registration_number", "[REGISTRATION NUMBER]")
        supplier_addr = supplier.get("address", "[ADDRESS]")
        supplier_state = self._extract_state(supplier_addr)
        
        # Customer (Buyer)
        pdf.cell(0, 5, f'(1) {buyer_name}, a company incorporated in {buyer_state} with registration number', ln=1)
        pdf.cell(0, 5, f'    {buyer_reg} and whose registered office is at {buyer_addr} (the "Customer"); and', ln=1)
        pdf.ln(2)
        
        # Supplier
        pdf.cell(0, 5, f'(2) {supplier_name}, a company incorporated in {supplier_state} with registration number', ln=1)
        pdf.cell(0, 5, f'    {supplier_reg} and whose registered office is at {supplier_addr} (the "Supplier").', ln=1)
        pdf.ln(5)
        
        # Section 1: GOODS AND SERVICES
        self._add_section(pdf, "1. GOODS AND SERVICES", bold=True)
        
        pdf.set_font('Arial', '', 10)
        pdf.cell(0, 5, '1.1 The Supplier shall provide the goods (the "Goods") as described in Section 1.2', ln=1)
        pdf.cell(0, 5, '    in accordance with the terms and conditions set out in this Agreement.', ln=1)
        pdf.ln(2)
        
        pdf.cell(0, 5, '1.2 The Goods to be provided by the Supplier include:', ln=1)
        pdf.ln(2)
        
        product_desc = f"{prod.get('product_name', '')} ({prod.get('sku', '')})"
        if prod.get('description'):
            product_desc += f": {prod.get('description', '')}"
        
        pdf.set_font('Arial', '', 10)
        for line in self._split_text(pdf, product_desc, 165):
            pdf.cell(5, 5, '', ln=0)  # Indent
            pdf.cell(0, 5, line, ln=1)
        
        pdf.ln(1)
        pdf.cell(5, 5, '', ln=0)
        pdf.cell(0, 5, f"Quantity: {prod.get('unit_quantity', '')} {prod.get('unit_of_measure', '')}", ln=1)
        pdf.cell(5, 5, '', ln=0)
        pdf.cell(0, 5, f"Unit Price: {prod.get('currency', 'USD')} {prod.get('agreed_unit_price', '0.00'):,.2f}", ln=1)
        pdf.cell(5, 5, '', ln=0)
        pdf.cell(0, 5, f"Total Contract Value: {prod.get('currency', 'USD')} {prod.get('total_contract_value', '0.00'):,.2f}", ln=1)
        pdf.ln(3)
        
        # Section 2: PAYMENT
        self._add_section(pdf, "2. PAYMENT", bold=True)
        
        pdf.set_font('Arial', '', 10)
        pdf.cell(0, 5, '2.1 The Customer shall pay the Supplier for the Goods in accordance with the following terms:', ln=1)
        pdf.ln(2)
        
        payment_terms = terms.get("payment_terms", "Payment terms to be specified.")
        pdf.set_font('Arial', '', 10)
        for line in self._split_text(pdf, payment_terms, 165):
            pdf.cell(5, 5, '', ln=0)
            pdf.cell(0, 5, line, ln=1)
        
        pdf.ln(1)
        pdf.cell(5, 5, '', ln=0)
        pdf.cell(0, 5, f"Total Amount: {prod.get('currency', 'USD')} {prod.get('total_contract_value', '0.00'):,.2f}", ln=1)
        pdf.ln(3)
        
        # Section 3: DELIVERY
        self._add_section(pdf, "3. DELIVERY", bold=True)
        
        pdf.set_font('Arial', '', 10)
        pdf.cell(0, 5, '3.1 The Supplier shall deliver the Goods to the following address:', ln=1)
        pdf.ln(2)
        
        shipping_addr = deliver.get("shipping_address", "")
        delivery_type = deliver.get("delivery_type", "")
        delivery_date = deliver.get("required_delivery_date", "")
        inspection_days = deliver.get("inspection_period_days", "")
        penalty = deliver.get("late_delivery_penalty", "")
        
        pdf.cell(5, 5, '', ln=0)
        for line in self._split_text(pdf, shipping_addr, 165):
            pdf.cell(0, 5, line, ln=1)
        pdf.ln(1)
        
        pdf.cell(0, 5, f'3.2 Delivery Type: {delivery_type}', ln=1)
        pdf.cell(0, 5, f'3.3 Required Delivery Date: {delivery_date}', ln=1)
        pdf.cell(0, 5, f'3.4 Inspection Period: {inspection_days} days from delivery', ln=1)
        if penalty:
            pdf.cell(0, 5, f'3.5 Late Delivery Penalty: {penalty}', ln=1)
        pdf.ln(3)
        
        # Section 4: WARRANTY
        self._add_section(pdf, "4. WARRANTY", bold=True)
        
        warranty = terms.get("warranty_period", "Warranty terms to be specified.")
        pdf.set_font('Arial', '', 10)
        pdf.cell(0, 5, '4.1 The Supplier warrants that:', ln=1)
        pdf.ln(2)
        pdf.cell(5, 5, '', ln=0)
        pdf.cell(0, 5, f'(a) The Goods will conform to the specifications and descriptions provided;', ln=1)
        pdf.cell(5, 5, '', ln=0)
        pdf.cell(0, 5, f'(b) {warranty}', ln=1)
        pdf.ln(3)
        
        # Section 5: LIABILITY
        self._add_section(pdf, "5. LIABILITY", bold=True)
        
        pdf.set_font('Arial', '', 10)
        pdf.cell(0, 5, '5.1 Neither party excludes or limits its liability for: (a) death or personal injury', ln=1)
        pdf.cell(0, 5, '    caused by its negligence; (b) fraud or fraudulent misrepresentation; or (c) any', ln=1)
        pdf.cell(0, 5, '    other liability that cannot be excluded or limited under applicable law.', ln=1)
        pdf.ln(2)
        
        indemnification = terms.get("indemnification_limit", "Capped at the total contract value.")
        pdf.cell(0, 5, '5.2 Subject to Clause 5.1, the Supplier\'s total liability arising under or in', ln=1)
        pdf.cell(0, 5, '    connection with this Agreement, whether in contract, tort (including negligence),', ln=1)
        pdf.cell(0, 5, '    breach of statutory duty, or otherwise, shall not exceed the total fees paid by', ln=1)
        pdf.cell(0, 5, '    the Customer to the Supplier under this Agreement.', ln=1)
        pdf.ln(2)
        
        for line in self._split_text(pdf, f"5.3 {indemnification}", 170):
            pdf.cell(0, 5, line, ln=1)
        pdf.ln(3)
        
        # Section 6: INTELLECTUAL PROPERTY RIGHTS
        self._add_section(pdf, "6. INTELLECTUAL PROPERTY RIGHTS", bold=True)
        
        pdf.set_font('Arial', '', 10)
        pdf.cell(0, 5, '6.1 All intellectual property rights in the Goods provided under this Agreement', ln=1)
        pdf.cell(0, 5, '    shall remain the property of the Supplier, unless otherwise agreed in writing.', ln=1)
        pdf.ln(3)
        
        # Section 7: CONFIDENTIALITY
        self._add_section(pdf, "7. CONFIDENTIALITY", bold=True)
        
        pdf.set_font('Arial', '', 10)
        pdf.cell(0, 5, '7.1 Each party agrees to keep the other party\'s Confidential Information', ln=1)
        pdf.cell(0, 5, '    confidential and to use it strictly for the performance of this Agreement.', ln=1)
        pdf.ln(3)
        
        # Section 8: TERM AND TERMINATION
        self._add_section(pdf, "8. TERM AND TERMINATION", bold=True)
        
        termination = terms.get("termination_clause", "Standard termination with 60-day written notice; immediate termination for material breach.")
        pdf.set_font('Arial', '', 10)
        pdf.cell(0, 5, '8.1 This Agreement shall commence on the Effective Date and shall continue', ln=1)
        pdf.cell(0, 5, '    until terminated in accordance with this Agreement.', ln=1)
        pdf.ln(2)
        
        for line in self._split_text(pdf, f'8.2 {termination}', 170):
            pdf.cell(0, 5, line, ln=1)
        pdf.ln(3)
        
        # Section 9: GOVERNING LAW AND JURISDICTION
        self._add_section(pdf, "9. GOVERNING LAW AND JURISDICTION", bold=True)
        
        governing_law = terms.get("governing_law", "State of Georgia")
        dispute_resolution = terms.get("dispute_resolution", "Binding arbitration in Atlanta, GA.")
        
        pdf.set_font('Arial', '', 10)
        pdf.cell(0, 5, f'9.1 This Agreement and any dispute or claim arising out of or in connection', ln=1)
        pdf.cell(0, 5, f'    with it shall be governed by and construed in accordance with the law of {governing_law}.', ln=1)
        pdf.ln(2)
        
        for line in self._split_text(pdf, f'9.2 {dispute_resolution}', 170):
            pdf.cell(0, 5, line, ln=1)
        pdf.ln(5)
        
        # Signatures Section
        pdf.set_font('Arial', 'B', 11)
        pdf.cell(0, 8, "IN WITNESS WHEREOF, the parties have executed this Agreement as of the Effective Date.", ln=1, align='C')
        pdf.ln(8)
        
        # Signature blocks
        buyer_contact = buyer.get("contact_information", {})
        supplier_contact = supplier.get("contact_information", {})
        
        # Company names
        pdf.set_font('Arial', 'B', 10)
        pdf.cell(90, 6, buyer_name, ln=0, align='L')
        pdf.cell(0, 6, supplier_name, ln=1, align='L')
        pdf.ln(10)
        
        # Signature blocks with lines right after "Signatory:" text
        pdf.set_font('Arial', '', 9)
        pdf.set_line_width(0.5)
        
        # Get starting position
        start_x_left = pdf.get_x()
        y_pos = pdf.get_y()
        
        # Left signature block (Buyer) - Write "Signatory:" and draw line immediately after
        signatory_text = "Signatory: "
        signatory_width = pdf.get_string_width(signatory_text)
        pdf.cell(signatory_width, 5, signatory_text, ln=0, align='L')
        
        # Draw line right after "Signatory:" text, extending to end of left column
        line_start_x = pdf.get_x() + 1  # Small gap after text
        line_end_x = start_x_left + 90  # End of left column
        pdf.line(line_start_x, y_pos + 4, line_end_x, y_pos + 4)
        
        # Right signature block (Supplier) - Position at right column
        start_x_right = 120  # Start of right column
        pdf.set_xy(start_x_right, y_pos)
        pdf.cell(signatory_width, 5, signatory_text, ln=0, align='L')
        
        # Draw line right after "Signatory:" text for right column
        line_start_x_right = pdf.get_x() + 1
        line_end_x_right = 190  # End of page width
        pdf.line(line_start_x_right, y_pos + 4, line_end_x_right, y_pos + 4)
        
        # Move to next line
        pdf.set_xy(start_x_left, y_pos + 8)
        pdf.ln(2)
        
        # Names
        pdf.set_font('Arial', '', 9)
        pdf.cell(90, 5, f"Name: {buyer_contact.get('buyer_name', '')}", ln=0, align='L')
        pdf.cell(0, 5, f"Name: {supplier_contact.get('supplier_name', '')}", ln=1, align='L')
        pdf.ln(3)
        
        # Titles
        pdf.cell(90, 5, f"Title: {buyer_contact.get('title', '')}", ln=0, align='L')
        pdf.cell(0, 5, f"Title: {supplier_contact.get('title', '')}", ln=1, align='L')
        pdf.ln(3)
        
        # Emails
        pdf.cell(90, 5, f"Email: {buyer_contact.get('email', '')}", ln=0, align='L')
        pdf.cell(0, 5, f"Email: {supplier_contact.get('email', '')}", ln=1, align='L')
        pdf.ln(3)
        
        # Date lines - draw lines right after "Date:" text
        start_x_left = pdf.get_x()
        y_pos = pdf.get_y()
        
        # Left date block
        date_text = "Date: "
        date_width = pdf.get_string_width(date_text)
        pdf.cell(date_width, 5, date_text, ln=0, align='L')
        
        # Draw line right after "Date:" text
        line_start_x = pdf.get_x() + 1
        line_end_x = start_x_left + 90
        pdf.line(line_start_x, y_pos + 4, line_end_x, y_pos + 4)
        
        # Right date line
        start_x_right = 120
        pdf.set_xy(start_x_right, y_pos)
        pdf.cell(date_width, 5, date_text, ln=0, align='L')
        line_start_x_right = pdf.get_x() + 1
        line_end_x_right = 190
        pdf.line(line_start_x_right, y_pos + 4, line_end_x_right, y_pos + 4)
        
        # Move to next line
        pdf.set_xy(start_x_left, y_pos + 8)
        pdf.ln(2)
        
        # File output
        if not output_path:
            base = c.get('order_reference_id', 'contract')
            safe_base = "".join([x if x.isalnum() or x in ('-', '_') else '_' for x in str(base)])
            today = datetime.datetime.now().strftime('%Y%m%d')
            output_path = f"{safe_base}_contract_{today}.pdf"
        pdf.output(output_path)
        return os.path.abspath(output_path)
    
    def _extract_state(self, address: str) -> str:
        """Extracts state/country from address"""
        # Try to extract state from US address (e.g., "GA", "California")
        states = {
            'AL': 'Alabama', 'AK': 'Alaska', 'AZ': 'Arizona', 'AR': 'Arkansas',
            'CA': 'California', 'CO': 'Colorado', 'CT': 'Connecticut', 'DE': 'Delaware',
            'FL': 'Florida', 'GA': 'Georgia', 'HI': 'Hawaii', 'ID': 'Idaho',
            'IL': 'Illinois', 'IN': 'Indiana', 'IA': 'Iowa', 'KS': 'Kansas',
            'KY': 'Kentucky', 'LA': 'Louisiana', 'ME': 'Maine', 'MD': 'Maryland',
            'MA': 'Massachusetts', 'MI': 'Michigan', 'MN': 'Minnesota', 'MS': 'Mississippi',
            'MO': 'Missouri', 'MT': 'Montana', 'NE': 'Nebraska', 'NV': 'Nevada',
            'NH': 'New Hampshire', 'NJ': 'New Jersey', 'NM': 'New Mexico', 'NY': 'New York',
            'NC': 'North Carolina', 'ND': 'North Dakota', 'OH': 'Ohio', 'OK': 'Oklahoma',
            'OR': 'Oregon', 'PA': 'Pennsylvania', 'RI': 'Rhode Island', 'SC': 'South Carolina',
            'SD': 'South Dakota', 'TN': 'Tennessee', 'TX': 'Texas', 'UT': 'Utah',
            'VT': 'Vermont', 'VA': 'Virginia', 'WA': 'Washington', 'WV': 'West Virginia',
            'WI': 'Wisconsin', 'WY': 'Wyoming'
        }
        
        # Try to find state abbreviation
        parts = address.split(',')
        if len(parts) >= 2:
            state_part = parts[-2].strip().upper()
            if state_part in states:
                return states[state_part]
            # Check if it's a full state name
            for abbr, name in states.items():
                if name.upper() in state_part.upper():
                    return name
        
        # Default to extracted part or generic
        if len(parts) >= 2:
            return parts[-2].strip()
        return "[STATE/COUNTRY]"
    
    def _add_section(self, pdf: FPDF, title: str, bold: bool = True):
        """Adds a section header with bold formatting and underline"""
        pdf.ln(2)
        if bold:
            pdf.set_font('Arial', 'B', 11)
        else:
            pdf.set_font('Arial', '', 11)
        
        # Get the starting x position and y position before writing
        start_x = pdf.get_x()
        y_before = pdf.get_y()
        
        # Write the title
        pdf.cell(0, 8, title, ln=1)
        
        # Calculate the width of the title text
        title_width = pdf.get_string_width(title)
        
        # Draw underline right under the text (starting from left margin)
        y_after = pdf.get_y()
        pdf.set_line_width(0.5)
        pdf.line(start_x, y_before + 7, start_x + title_width, y_before + 7)
        
        pdf.ln(2)

    @staticmethod
    def from_json_file(json_path: str) -> 'ContractAgent':
        """
        Loads a contract from a JSON file path.
        """
        with open(json_path, 'r') as f:
            data = json.load(f)
        return ContractAgent(data)

if __name__ == "__main__":
    import sys
    if len(sys.argv) < 2:
        print("Usage: python contract_agent.py <path_to_json_file>")
        sys.exit(1)

    json_path = sys.argv[1]
    print(f"Loading contract data from {json_path}...")

    agent = ContractAgent.from_json_file(json_path)
    output_path = agent.generate_contract_pdf()

    print(f"✅ Contract PDF generated successfully: {output_path}")
